### ISSUE TITLE
ip 주소 노출 대신 random_id 노출하는 방법

### ISSUE THREAD

**Issue by cbcruk** [justinaus/achat#1]
https://github.com/justinaus/achat/blob/0c7b67d0a15850ebdb2c3ede2335086ae389eb79/server/server.js#L44

혹시나 나중에 ip는 주소 노출여부에 따른 이슈가 있을수도 있으므로 블라인드 처럼 [random_id](https://github.com/dylang/shortid)로 노출하는 방법도 검토해봐야 할 듯 싶습니다.

**Comment by justinaus** [comment]
익명이기는 하지만 어느 정도는 아이덴티티를 갖고자 일단은 ip를 노출하는 것으로 합니다.
그리고 뒤의 'test' 부분은 테스트 용으로 붙인 것입니다. 실 배포 때는 사라질 부분입니다.
ex) 123.45.67.x.
